/**
 * Expo config plugin: adopt the UIKit UIScene lifecycle.
 *
 * iOS 27's SDK makes scene adoption MANDATORY — an app built against it that
 * still uses the legacy `application(_:didFinishLaunchingWithOptions:)` + window
 * path is killed at launch with:
 *   "UIScene life cycle is required for apps built with this SDK."
 *
 * Expo SDK 57 / React Native 0.86 don't ship a SceneDelegate yet (their
 * AppDelegate creates the UIWindow directly), so we add one. Because `ios/` is
 * regenerated by `expo prebuild`, this must be a plugin, not a hand edit.
 *
 * What it does:
 *   1. Info.plist — add a UIApplicationSceneManifest whose single configuration
 *      names `$(PRODUCT_MODULE_NAME).SceneDelegate` as the scene delegate class.
 *   2. Writes ios/<Name>/SceneDelegate.swift — creates the window bound to the
 *      UIWindowScene and starts React Native using the AppDelegate's existing
 *      RCTReactNativeFactory (RN's `startReactNative(...inWindow:)` sets the
 *      rootViewController + makeKeyAndVisible on the window we pass).
 *   3. AppDelegate.swift — remove the legacy window creation / startReactNative
 *      (the scene now owns the window) while keeping the factory setup, and make
 *      the factory reachable from the scene.
 *   4. Registers SceneDelegate.swift in the Xcode project (sources build phase).
 *
 * The RN root view + factory are unchanged; we only move WHO creates the window.
 */

const {
  withInfoPlist,
  withAppDelegate,
  withXcodeProject,
  withDangerousMod,
  IOSConfig,
} = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const SCENE_DELEGATE_CLASS = "SceneDelegate";

// ── 1. Info.plist: scene manifest pointing at our delegate ───────────────────
function withSceneManifest(config) {
  return withInfoPlist(config, (cfg) => {
    cfg.modResults.UIApplicationSceneManifest = {
      UIApplicationSupportsMultipleScenes: false,
      UISceneConfigurations: {
        UIWindowSceneSessionRoleApplication: [
          {
            UISceneConfigurationName: "Default Configuration",
            UISceneDelegateClassName: `$(PRODUCT_MODULE_NAME).${SCENE_DELEGATE_CLASS}`,
          },
        ],
      },
    };
    return cfg;
  });
}

// ── 2. Write SceneDelegate.swift ─────────────────────────────────────────────
function sceneDelegateSource() {
  return `import UIKit
import React

// Added by plugins/withSceneLifecycle.js to adopt the UIScene lifecycle required
// by the iOS 27 SDK. Creates the window for the connecting scene and starts
// React Native via the AppDelegate's existing RCTReactNativeFactory.
//
// IMPORTANT: once a SceneDelegate exists, iOS routes deep links / universal
// links to the SCENE, not the AppDelegate — so the AppDelegate's
// open-url / continue-userActivity methods stop firing and
// Linking.getInitialURL() would return nil. We forward all link entry points to
// RCTLinkingManager here (cold launch via connectionOptions, warm via the
// scene open/continue callbacks).
class ${SCENE_DELEGATE_CLASS}: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard let windowScene = scene as? UIWindowScene else { return }
    guard let appDelegate = UIApplication.shared.delegate as? AppDelegate,
          let factory = appDelegate.reactNativeFactory else { return }

    let window = UIWindow(windowScene: windowScene)
    self.window = window
    // RN sets window.rootViewController + makeKeyAndVisible internally.
    factory.startReactNative(withModuleName: "main", in: window, launchOptions: nil)

    // Cold-launch deep link (custom scheme) → RN Linking.getInitialURL().
    if let urlContext = connectionOptions.urlContexts.first {
      RCTLinkingManager.application(
        UIApplication.shared,
        open: urlContext.url,
        options: [:]
      )
    }
    // Cold-launch universal link.
    for userActivity in connectionOptions.userActivities
    where userActivity.activityType == NSUserActivityTypeBrowsingWeb {
      RCTLinkingManager.application(
        UIApplication.shared,
        continue: userActivity,
        restorationHandler: { _ in }
      )
    }
  }

  // Warm deep link (custom scheme) while the app is running.
  func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
    guard let url = URLContexts.first?.url else { return }
    RCTLinkingManager.application(UIApplication.shared, open: url, options: [:])
  }

  // Warm universal link while the app is running.
  func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
    RCTLinkingManager.application(
      UIApplication.shared,
      continue: userActivity,
      restorationHandler: { _ in }
    )
  }
}
`;
}

function withSceneDelegateFile(config) {
  return withDangerousMod(config, [
    "ios",
    (cfg) => {
      const name = cfg.modRequest.projectName;
      const dir = path.join(cfg.modRequest.platformProjectRoot, name);
      fs.writeFileSync(path.join(dir, `${SCENE_DELEGATE_CLASS}.swift`), sceneDelegateSource());
      return cfg;
    },
  ]);
}

// ── 3. Strip legacy window bootstrap from AppDelegate ────────────────────────
function withPatchedAppDelegate(config) {
  return withAppDelegate(config, (cfg) => {
    const src = cfg.modResults.contents;

    // Already patched (idempotent across prebuilds) — nothing to do.
    if (src.includes("handled by SceneDelegate")) {
      return cfg;
    }

    // Remove the `#if os(iOS)... startReactNative ... #endif` window bootstrap.
    // The scene creates the window now; the factory is still built above.
    const anchor = /#if os\(iOS\) \|\| os\(tvOS\)[\s\S]*?factory\.startReactNative\([\s\S]*?\)\s*#endif\s*/;

    if (!anchor.test(src)) {
      // FAIL LOUDLY: if the Expo AppDelegate template changed and we can't strip
      // the legacy window bootstrap, leaving both the AppDelegate window AND the
      // SceneDelegate window active causes a black screen / crash. Better to fail
      // the build with a clear message than ship a broken app (esp. on EAS).
      throw new Error(
        "[withSceneLifecycle] Could not find the legacy window bootstrap in " +
          "AppDelegate.swift to remove. The Expo AppDelegate template likely " +
          "changed. Update the anchor regex in plugins/withSceneLifecycle.js so " +
          "the AppDelegate and SceneDelegate don't both create a window.",
      );
    }

    cfg.modResults.contents = src.replace(
      anchor,
      "// Window + React Native start now handled by SceneDelegate (iOS 27 scene lifecycle).\n",
    );
    return cfg;
  });
}

// ── 4. Register SceneDelegate.swift in the Xcode project ─────────────────────
function withSceneDelegateInXcode(config) {
  return withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    const name = cfg.modRequest.projectName;
    const filePath = `${name}/${SCENE_DELEGATE_CLASS}.swift`;

    // Skip if already added (idempotent across prebuilds).
    if (project.hasFile(filePath)) return cfg;

    IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
      filepath: filePath,
      groupName: name,
      project,
    });
    return cfg;
  });
}

module.exports = (config) => {
  config = withSceneManifest(config);
  config = withSceneDelegateFile(config);
  config = withPatchedAppDelegate(config);
  config = withSceneDelegateInXcode(config);
  return config;
};
