/**
 * Expo config plugin: force every CocoaPods target's iOS deployment target up to
 * the project floor during `pod install`.
 *
 * Xcode 27's minimum supported deployment target is iOS 15.0. A few transitive
 * pods (and CocoaPods' own aggregate/default) still declare 11.0 / 12.0 / 12.4,
 * which Xcode 27 flags as warnings (and can escalate to build errors). Expo's
 * `expo-build-properties` sets the app + most pods to our floor, but doesn't
 * rewrite every straggler config, so we do it in `post_install`.
 *
 * `ios/` is gitignored and regenerated by `expo prebuild`, so this MUST live in a
 * config plugin (Podfile edits by hand don't survive). We append a snippet to the
 * generated Podfile's existing `post_install` block via a dangerous mod.
 *
 * Floor: read from ios.deploymentTarget (expo-build-properties) via
 * Podfile.properties.json, defaulting to 16.4 to match app.json.
 */

const { withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const MARKER = "# cairn: bump pod deployment targets";

module.exports = (config) => {
  return withDangerousMod(config, [
    "ios",
    (cfg) => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, "Podfile");
      let contents = fs.readFileSync(podfile, "utf8");

      // Idempotent: skip if already injected (prebuild without --clean re-runs mods).
      if (contents.includes(MARKER)) return cfg;

      // The snippet raises any target below the floor. Uses the Podfile's own
      // `podfile_properties` (already parsed at the top of the generated Podfile).
      const snippet = `
    ${MARKER}
    min_ios = (podfile_properties['ios.deploymentTarget'] || '16.4')
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |bc|
        current = bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
        if current.nil? || current.to_f < min_ios.to_f
          bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = min_ios
        end
      end
    end
`;

      // Inject just before the closing `end` of the `post_install do |installer|`
      // block. That block ends the file's target block; we find the LAST
      // `react_native_post_install(...)` call's enclosing block and append after it.
      const anchor = /(react_native_post_install\([\s\S]*?\)\s*\n)/;
      if (anchor.test(contents)) {
        contents = contents.replace(anchor, `$1${snippet}`);
      } else {
        // Fallback: append a fresh post_install if the RN one isn't present.
        contents += `
post_install do |installer|
${snippet}end
`;
      }

      fs.writeFileSync(podfile, contents);
      return cfg;
    },
  ]);
};
