/**
 * Expo config plugin: make the iOS status bar adapt to light/dark automatically
 * WITHOUT a runtime JS flash.
 *
 * The app is `UIUserInterfaceStyle=Automatic` (follows the OS). With
 * `UIViewControllerBasedStatusBarAppearance=false` (the RN/Expo default, kept so
 * the react-native StatusBar API still works) iOS resolves
 * `UIStatusBarStyleDefault` at the WINDOW level per appearance: dark content in
 * light mode, light content in dark mode — exactly what we want, resolved
 * natively and instantly.
 *
 * We therefore do NOT drive the status bar from JS. Doing so (expo-status-bar /
 * setStatusBarStyle) fought this native window default during appearance changes
 * and produced a white→black flash when switching to light mode. See
 * https://github.com/expo/expo/issues/8002.
 *
 * `ios/` is regenerated by `expo prebuild`, so these Info.plist values are pinned
 * here rather than edited in the generated plist.
 */

const { withInfoPlist } = require("@expo/config-plugins");

module.exports = (config) => {
  return withInfoPlist(config, (cfg) => {
    // Window-level, appearance-adaptive status bar. "Default" = dark content on
    // light backgrounds, light content on dark backgrounds when the app follows
    // the system appearance (UIUserInterfaceStyle=Automatic).
    cfg.modResults.UIStatusBarStyle = "UIStatusBarStyleDefault";
    // Keep window-based (not view-controller-based) appearance so the value
    // above governs and the RN StatusBar API remains available if ever needed.
    cfg.modResults.UIViewControllerBasedStatusBarAppearance = false;
    return cfg;
  });
};
