/**
 * Cairn — "What's New" feature source of truth (curated).
 *
 * This is the hand-authored list of MAJOR, user-facing features surfaced in the
 * What's New modal (src/components/layout/NewFeatureModal.tsx). It is the input
 * to scripts/generate-features.js, which validates it and writes the baked
 * src/generated/new-features.json the app reads at runtime — mirroring how
 * scripts/generate-licenses.js turns the curated ROLE_MAP into licenses.json.
 *
 * ── When to add an entry ──────────────────────────────────────────────────────
 * Add an entry ONLY for a major, headline feature a user would want announced on
 * launch — not every changelog line (fixes, small tweaks, and internal work stay
 * in changelogs/ only). Append new entries at the END, in release order; the
 * modal auto-shows unseen entries belonging to the newest `version` present.
 *
 * ── Entry shape ───────────────────────────────────────────────────────────────
 *   id          Stable unique key, e.g. "v2.5.9-saved-providers". NEVER reuse or
 *               renumber — it's how "already seen" is tracked per user.
 *   version     Release tag string, e.g. "v2.5.9". Group multiple features of the
 *               same release under the same version.
 *   title       Short headline (a few words).
 *   category    One-word-ish label shown as the eyebrow (e.g. "AI Chat", "Agent").
 *   description  One or two sentences of context.
 *   highlights  3–4 bullet strings. "Prefix: rest" bolds the prefix in the modal.
 *
 * @typedef {{ id: string, version: string, title: string, category: string,
 *             description: string, highlights: string[] }} NewFeature
 * @type {NewFeature[]}
 */
const FEATURES = [
  {
    id: "v1.5.0-obsidian",
    version: "v1.5.0",
    title: "Obsidian Vault Compatibility",
    category: "Integrations",
    description: "Cairn is now fully compatible with Obsidian vaults, operating seamlessly side-by-side.",
    highlights: [
      "Obsidian Vault Interoperability: Point any Cairn workspace directly to an Obsidian folder without breaking configuration files.",
      "Double-Bracket Image Embeds: Render Obsidian-style `![[image.png]]` media links natively inside the Markdown previewer and editor.",
      "Vault-Aware Assets: Pasted and uploaded assets are saved directly to your vault's `attachments/` folder.",
      "Preservation YAML Sync: Modifying note metadata in Cairn preserves external Obsidian aliases, dates, or custom YAML tags.",
    ],
  },
  {
    id: "v1.6.0-decoupled-ai",
    version: "v1.6.0",
    title: "Decoupled AI Configurations",
    category: "AI Chat",
    description: "Configure different models for daily AI chat versus complex coding agent loops.",
    highlights: [
      "Independent Parameters: Run lightweight, on-device models for inline editor actions while using large cloud endpoints for coding loops.",
      "Domain Partitioned Settings: Separated AI settings panels divide General Chat/MCP from Coding Agent (Pi) context parameters.",
      "Sync & Migration: Credential configurations are synchronized across General Chat and Agent loops upon first setup.",
    ],
  },
  {
    id: "v1.7.0-local-llm",
    version: "v1.7.0",
    title: "Local LLM Integration",
    category: "Local AI",
    description: "Full cross-platform local engine routing inference offline to local llama-server binaries.",
    highlights: [
      "1-Click Binary Downloader: Automatically downloads, unpacks, and executes ggml llama-server setups customized for your platform.",
      "CDN Toggle Mirroring: Alternate model weight downloads between Hugging Face and high-speed regional CDN mirrors.",
      "Self-Healing XML Parser: Stream repairs to malformed JSON output blocks generated by smaller quantized local models.",
      "Star Toggle: Select downloaded weights to launch automatically on app startup without manual model load.",
    ],
  },
  {
    id: "v1.8.0-mobile-companion",
    version: "v1.8.0",
    title: "Mobile Companion Service",
    category: "Mobile",
    description: "Secure, local-network mobile access to Cairn notes, boards, and agents.",
    highlights: [
      "Mobile QR Code Pairing: Scan pairing QR codes or enter single-use PINs to launch secure mobile client sessions.",
      "Mobile Responsive Layouts: Sidebar collapsible drawers, swipeable settings categories, and dynamic content scaling.",
      "Touch DnD Support: Holds and scrolls on touchscreens cede canvas pointer control instantly to board DnD sensors.",
      "Web Share PDF Export: Generate standard print-layout PDFs and export them directly to native mobile share sheets.",
    ],
  },
  {
    id: "v2.0.0-codebase-agent",
    version: "v2.0.0",
    title: "Codebase Indexing & Agent Guardrails",
    category: "Agent",
    description: "AST-free regex symbol indexers and live execution confirmations.",
    highlights: [
      "Semantic Codebase Indexing: Incremental parser mapping functions, classes, and call graph relations for Rust, Go, Python, and JS.",
      "Plan & Execute Toggles: Lower temperature Outline settings for safe, deterministic planning drafts.",
      "Modifying Tool Confirmation: Security gate pausing execution for inline Confirm/Deny tool approval in message bubbles.",
    ],
  },
  {
    id: "v2.1.1-semantic-search",
    version: "v2.1.1",
    title: "Local Semantic Search",
    category: "Knowledge Graph",
    description: "Find related notes by meaning — powered by a local embedding model that runs fully offline.",
    highlights: [
      "Semantic Neighbours: A packaged on-device embedding model links notes by meaning; the Knowledge Graph gains a \"semantic\" edge type and the editor's Backlinks panel shows the most similar notes with score bars.",
      "Section-Based Embeddings: Notes are split by headings so each section gets its own vector — multi-topic notes connect to the right clusters instead of averaging their signal away.",
      "Fully Offline: Inference runs in a local background worker (ONNX Runtime); nothing is sent to a cloud service.",
      "Edge Hover Tooltips: Hovering a semantic link shows the two note/section titles and the similarity percentage.",
    ],
  },
  {
    id: "v2.2.0-thinking-stream",
    version: "v2.2.0",
    title: "Reasoning & Thinking Streams",
    category: "AI Chat",
    description: "Peek behind the curtain to observe the model's logic as it streams in real-time.",
    highlights: [
      "Collapsible Thinking Blocks: Follow the model's reasoning stream. Blocks auto-collapse once generation starts.",
      "Context & Usage Metrics: View exact breakdown of answer tokens vs reasoning tokens in the ContextRing popover.",
    ],
  },
  {
    id: "v2.3.0-git-workflow",
    version: "v2.3.0",
    title: "Polished Git Integrations",
    category: "Git",
    description: "Streamlined branch management and file discarding controls.",
    highlights: [
      "Radix Branch Switcher: Search, filter, and switch branches quickly, or create new branches from a dedicated dialog.",
      "File-Level & Bulk Discarding: Clean your workspace by discarding specific changes or sections with verification prompts.",
      "Action Tooltips: Custom theme-aware tooltips details for all stage, unstage, commit, and discard actions.",
    ],
  },
  {
    id: "v2.3.0-chat-layout",
    version: "v2.3.0",
    title: "Dynamic Chat Layout & Previews",
    category: "AI Chat",
    description: "Work with notes and tasks side-by-side during AI chats.",
    highlights: [
      "Dynamic Layout Morphing: Toggle the chat between right-docked sidebar and full workspace modes smoothly.",
      "Side-by-Side Context Previews: Click references, tasks, or notes in assistant responses to view them instantly next to your chat.",
      "Direct Workspace Navigation: Jump straight to the board or notes workspace directly from the preview header.",
    ],
  },
  {
    id: "v2.3.2-onboarding-tour",
    version: "v2.3.2",
    title: "Interactive Workspace Tour & Highlights",
    category: "Workspace Help",
    description: "Learn your way around the workspaces with visual guided tours and feature slides.",
    highlights: [
      "Guided Workspace Tour: Step through an interactive, visual tour explaining Overview, Notes, Board, and Flow views.",
      "Real-Time Transition Cutout: Highlight portal adapts instantly to window resizing and CSS sliding panel drawers.",
      "What's New Modal: Paginated carousel modal highlights new updates automatically on launch.",
      "Skip All Controls: Skip remaining slide cards instantly and mark everything as seen to prevent boot prompts.",
    ],
  },
  {
    id: "v2.3.4-calendar",
    version: "v2.3.4",
    title: "Calendar View",
    category: "Planning",
    description: "Schedule tasks by due date and see what's overdue at a glance.",
    highlights: [
      "Month & Week Layouts: A project-scoped calendar (⌘4) lays out task cards by due date with prev / next / today navigation.",
      "Drag to Reschedule: Drag any task onto a different day to change its due date — an optimistic, fully undoable update.",
      "Overdue & Unscheduled Trays: A past-due banner and a collapsible no-due-date tray let you drag tasks straight onto a day to schedule them.",
      "Day Detail Modal: Packed days show a \"+N more\" affordance opening a list of everything due that day.",
    ],
  },
  {
    id: "v2.3.4-external-tools",
    version: "v2.3.4",
    title: "External Tools — MCP Servers & HTTP APIs",
    category: "AI Tools",
    description: "Connect the AI chat and agent to remote MCP servers and any HTTP API.",
    highlights: [
      "Settings → Tools: Add remote MCP servers (SSE or streamable-HTTP) and expose any HTTP API as a single tool, each with an enable toggle and Test connection button.",
      "Per-Project Attach: Attach tools per-project from the Overview → Tools panel so each project only sees the tools it needs.",
      "AI Tool Builder: Describe an endpoint in plain English; the builder probes it live, figures out the auth and response shape, and trims it to just the useful fields to save tokens.",
      "Secure Credentials: API keys and tokens live in your OS keychain (Keychain / DPAPI / libsecret) — never in the database, plain text, or sent to the AI model.",
    ],
  },
  {
    id: "v2.3.4-mcp-oauth",
    version: "v2.3.4",
    title: "OAuth Sign-in for Remote MCP Servers",
    category: "AI Tools",
    description: "Connect to MCP servers that gate access behind a sign-in page — Figma, Linear, Notion, GitHub, and more.",
    highlights: [
      "One-Click Sign In: Choose OAuth as the auth mode, click Sign in, approve in your browser, and you're redirected back via a cairn:// deep link.",
      "Full OAuth 2.1 Flow: Server discovery, dynamic client registration, PKCE, token exchange, and automatic refresh are handled for you by the MCP SDK.",
      "Keychain-Backed Tokens: Access and refresh tokens are encrypted in your OS keychain and never exposed to the AI model or the app's UI layer.",
      "Connection Status: A Connected / Sign out control shows each server's auth state at a glance.",
    ],
  },
  {
    id: "v2.5.9-saved-providers",
    version: "v2.5.9",
    title: "Saved AI Providers",
    category: "AI Chat",
    description: "Save several AI connections and switch between them in a click — no more retyping endpoints and keys.",
    highlights: [
      "Named Connections: Save multiple OpenAI-compatible providers (OpenAI, OpenRouter, a local Ollama / LM Studio server…) each with its own base URL, key, and model, and switch the active one from a dropdown.",
      "Shared With The Coding Agent: Chat and the coding agent draw from the same provider list but keep independent selections — run the agent on a bigger model while chat stays on a cheaper one.",
      "Per-Surface Model Picker: A searchable model dropdown (with Refresh and a custom-model option) sits under the switcher, so each surface can use a different model on the same provider.",
      "Keys In Your OS Keychain: Provider API keys are stored encrypted in your operating system's keychain — never in plain text — and moved there automatically from any existing setup.",
    ],
  },
  {
    id: "v2.5.9-merge-projects",
    version: "v2.5.9",
    title: "Merge Projects",
    category: "Projects",
    description: "Consolidate two projects into one — move all notes, tasks, columns, and Idea Flow nodes across, then drop the empty project.",
    highlights: [
      "One Action: Open a project's ⋯ menu, choose Merge into…, and pick the destination project.",
      "Everything Moves: Notes, task cards, board columns, and Idea Flow nodes are all repointed to the destination in a single transactional move.",
      "Smart Board Merge: Cards land in the destination's matching column by type (Todo → Todo, Done → Done), and custom columns are recreated so nothing is lost.",
      "Great For Cleanup: The tidy way to consolidate duplicate or overlapping projects — including two projects that accidentally share a name.",
    ],
  },
];

module.exports = { FEATURES };
